### ISSUE TITLE
Account ID shouldn't exposed

### ISSUE THREAD

**Issue by flightlesstux** [bervProject/lambda-sharp#104]
Hi,

If it's your real account id, you shouldn't expose to the public : ) ref: https://github.com/bervProject/lambda-sharp/blob/efda4f11294adcfa5f21d59813dfeaabdfe9066c/terraform/main.tf#L54

Best

**Comment by berviantoleo** [comment]
Thanks. I'll try to remove those account ids.

**Comment by berviantoleo** [comment]
I closed this one. Thanks for reminding me. It might take a long time until the history is deleted.
